
description: K1Plaza Blank Starter

# widgets:
#   Gallery:
#     home_slider:
#       title: Home Slider
#     equipe:
#       title: Nossa Equipe
#   Blog:
#     blog:
#       title: Blog
#     noticias:
#       title: Notícias
#   Expo:
#     portfolio:
#       title: Portfolio
#     produtos:
#       title: Produtos